### ISSUE TITLE
Improve front page and dashboard layout on mobile

### ISSUE THREAD

**Issue by GreenReaper** [wbstack/ui#127]
As shown below, the front page and dashboard do not work so well on mobile, especially vertically. (Horizontally, the site selector widget is still cut off.)

Technically, it can be used, but it's not *usable* and does not give a good first impression. CSS using media queries (or just moving from a 2 or 3 column layout to 1 or 2 respectively) could work wonders.

![Screenshot_20210502-054003_Chrome_Beta](https://user-images.githubusercontent.com/383043/116802230-3b20e900-ab09-11eb-8c11-cd788be3d320.png)
![Screenshot_20210502-054108_Chrome_Beta](https://user-images.githubusercontent.com/383043/116802232-3bb97f80-ab09-11eb-9254-4e482cdb3e45.png)

**Comment by addshore** [comment]
Another example we should check
![image](https://user-images.githubusercontent.com/3308769/117449531-0614fc00-af38-11eb-93d9-bde1e280e3a0.png)

this is Chrome in mac OSc
(2560 x 1600)

**Comment by GreenReaper** [comment]
The issue there seems to be whatever is causing:
> @(min-width: 960px) .container {max-width:900px}

It can be reproduced by increasing page scaling to 133% - or 110% on a high-DPI screen that is already 125%. Most likely the MacOS device has a higher DPI. Possibly some mobile devices do, too.

Removing that rule seems to work up to ~150% DPI. After that my own site name is abbreviated and the Manual Stats (Feb 2021) overflows. Removing the left/right 8.333% columns avoids this, and even at 200% at least the "Your Wikis" text does not overflow.

**Comment by deer-wmde** [comment]
moved to phabricator: https://phabricator.wikimedia.org/T357104
