### ISSUE TITLE
Determine and display maximum upload size of site logo

### ISSUE THREAD

**Issue by GreenReaper** [wbstack/ui#285]
The dashboard states that users should "Upload a square PNG logo that is at least 135x135 pixels." A maximum file size or pixel dimension is not specified. However, a user on the Wikibase community user group chat found that a square 1.8MB upload only worked when they reduced the file size, so clearly there is a limit.

It's not clear to me exactly where the limit is, but perhaps during the interaction with the API? nginx/default. conf appears to be trying to allow very large files with ```client_max_body_size 1026g;``` (perhaps a *little* too high) - the default is 1m (1MB).

I think the equivalent for Apache would be LimitRequestBody. If PHP were involved, post_max_size and upload_max_filesize could also impact it; other languages have similar limits. ImageMagick can also be limited by policy.

The execution path appears to be src/components/Pages/ManageWiki/Cards/Logo.vue#L48 -> src/store/wikis.js#L142 -> src/backend/api.js#L35 -> wbstack/api/routes/api.php#L38 -> wbstack/api/app/Http/Controllers/WikiLogoController.php#L22

---

In the long term, a small PNG icon may need reconsideration. It's already not ideal, [looking fuzzy at higher resolutions](https://furry.wiki.opencura.com/?useskinversion=1), though [recent changes to Vector](https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Features/Header) make small icons more feasible because [icon dimensions are smaller](https://furry.wiki.opencura.com/?useskinversion=2) - this requires [appropriate CSS](https://furry.wiki.opencura.com/wiki/MediaWiki:Vector.css). [$wgLogos](https://www.mediawiki.org/wiki/Manual:$wgLogos) shows that current skin logo support is in transition, however it will be important to support SVG as an option.

**Comment by deer-wmde** [comment]
moved to phabricator https://phabricator.wikimedia.org/T357103
