### ISSUE TITLE
Clarify docs and references to wbstack.com <-> wikibase.cloud

### ISSUE THREAD

**Issue by lubianat** [wbstack/ui#661]
Talking with @tarrow  here at the hackathon in the docs session; it could be clearer if references to WBSTACK and wbstack.com are deprecated. 

Maybe one or two lines in READMEs, and updating GitHub repository descriptions could already be enough. Perhaps add a "wikibase.cloud" tag too. 

By description I mean these: 

![image](https://github.com/wbstack/ui/assets/7917951/ccf64bde-32e5-402f-aa1c-f7be27605af3)

**Comment by addshore** [comment]
It may still make sense to have some divide, depending on the teams future of the platform and stack.
The whole idea always was that other people can setup their own wbstack setup.
As time has progressed that's likely got harder to do with the pulling in of extra services not in kubernetes, but defintly still possible.

**Comment by deer-wmde** [comment]
moved to phabricator: https://phabricator.wikimedia.org/T357102
