### ISSUE TITLE
Have some sort of stats about current existing wikibases on wbstack on the home page.

### ISSUE THREAD

**Issue by addshore** [wbstack/ui#93]
> eg
> 
> ![image](https://user-images.githubusercontent.com/3308769/79382391-57cc9c00-7f5b-11ea-9426-912f9fdc42d7.png)
> 
> Which is from:
> 
> ```
> SELECT wiki_id, sitename, domain, count(*) as edits
> FROM event_page_updates as event
> LEFT JOIN wikis ON wikis.id = wiki_id
> WHERE event.created_at >  DATE(NOW() - INTERVAL 1 MONTH)
> AND wikis.deleted_at IS NULL
> GROUP BY wiki_id
> ORDER BY edits DESC
> LIMIT 10
> ```

**Comment by GreenReaper** [comment]
This seems good for seeing newly-registered wikis that are active, but established sites can become more active over time (for good/bad reasons).

You might also want some internal review tool for spam of all wikis, like the ratio of different users to recent edits (often, one account is made per edit).

The front page of such sites can also be empty, so given WBStack's focus it may be worth also linking to [Special:AllPages](https://programs.wiki.opencura.com/wiki/Special:AllPages?namespace=120) and/or recent changes.

Other list/"interesting wiki" ideas to consider:
* Sites using Lexemes and/or Schemas at all
* Counts of these, as well as items and properties
* Sites using Cradle - maybe Project:Cradle exists
* Sites with tagged Cradle or Quickstatements edits ("Widar [1.0.3]")
* Use of the equivalent properties/items features
* Federated properties being enabled
* Customisation of the icon, sidebar and license
* Having bothered to make a main page
* Talk namespace edits (any odd namespace)
* Numbers of users beyond one (though again, a large number of users might be a spam sign)
* Ratio of statements to items

**Comment by deer-wmde** [comment]
https://www.wikibase.cloud/discovery
